---
- name: Restart
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true
  sudo: yes

- name: Wait for restart to finish
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  sudo: no
